import '../models/member_model.dart';

class MemberService {
  // Simulated data
  static List<Member> getDummyMembers() {
    return [
      Member(
        id: '1',
        name: 'Sarah Johnson',
        role: 'CEO',
        company: 'TechStart Innovation',
        imageUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
        interests: ['AI', 'Startups', 'Venture Capital'],
        bio: 'Building the future of AI-driven startups',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '2',
        name: 'Michael Smith',
        role: 'CTO',
        company: 'NextGen Solutions',
        imageUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
        interests: ['Blockchain', 'Cybersecurity', 'IoT'],
        bio: 'Transforming technology with blockchain and IoT',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '3',
        name: 'Jessica Brown',
        role: 'Product Manager',
        company: 'Innova Labs',
        imageUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
        interests: ['Product Design', 'User Experience', 'Agile'],
        bio: 'Passionate about building user-centered products',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '4',
        name: 'David Wilson',
        role: 'Software Engineer',
        company: 'AlphaCode',
        imageUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
        interests: ['Machine Learning', 'Backend Development'],
        bio: 'Engineer with a love for ML and backend systems',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '5',
        name: 'Emily Davis',
        role: 'Marketing Lead',
        company: 'GrowthWave',
        imageUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
        interests: ['Digital Marketing', 'Brand Strategy', 'Content'],
        bio: 'Helping brands grow in the digital world',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '6',
        name: 'John Taylor',
        role: 'Data Scientist',
        company: 'DataFusion',
        imageUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
        interests: ['Data Science', 'AI', 'Predictive Analytics'],
        bio: 'Exploring insights from data with AI',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '7',
        name: 'Sophia Anderson',
        role: 'Design Lead',
        company: 'Creatify Studio',
        imageUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
        interests: ['UX Design', 'Visual Arts', 'Branding'],
        bio: 'Crafting seamless user experiences and visuals',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '8',
        name: 'Robert Thomas',
        role: 'Finance Manager',
        company: 'ClearFund',
        imageUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
        interests: ['Finance', 'Investment', 'Economics'],
        bio: 'Focused on finance and investment strategies',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '9',
        name: 'Laura Martinez',
        role: 'HR Specialist',
        company: 'PeopleFirst HR',
        imageUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
        interests: ['Human Resources', 'Talent Acquisition'],
        bio: 'Bringing talent and opportunities together',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '10',
        name: 'James White',
        role: 'Business Analyst',
        company: 'Insightful Analytics',
        imageUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
        interests: ['Business Strategy', 'Data Analysis'],
        bio: 'Analyzing data to drive business success',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '11',
        name: 'Megan Harris',
        role: 'Operations Manager',
        company: 'Streamline Ops',
        imageUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
        interests: ['Operations', 'Logistics', 'Process Improvement'],
        bio: 'Optimizing processes for efficient operations',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '12',
        name: 'Daniel Clark',
        role: 'Sales Executive',
        company: 'ExpandSales',
        imageUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
        interests: ['Sales', 'Customer Success', 'Networking'],
        bio: 'Building relationships that drive sales',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '13',
        name: 'Anna Lewis',
        role: 'Content Strategist',
        company: 'StoryWorks',
        imageUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
        interests: ['Content Marketing', 'Writing', 'SEO'],
        bio: 'Creating stories that engage and convert',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '14',
        name: 'Ryan Walker',
        role: 'Network Engineer',
        company: 'NetSecure',
        imageUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
        interests: ['Networking', 'Cybersecurity', 'Infrastructure'],
        bio: 'Securing and managing IT infrastructures',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '15',
        name: 'Emma Hall',
        role: 'UI Developer',
        company: 'BrightDesign',
        imageUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
        interests: ['Web Design', 'Frontend Development', 'CSS'],
        bio: 'Creating visually appealing user interfaces',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '16',
        name: 'Chris Allen',
        role: 'Supply Chain Specialist',
        company: 'LogiPro',
        imageUrl: 'https://randomuser.me/api/portraits/men/16.jpg',
        interests: ['Supply Chain', 'Logistics', 'Inventory'],
        bio: 'Efficient supply chain management solutions',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '17',
        name: 'Olivia Young',
        role: 'Research Analyst',
        company: 'Insight Labs',
        imageUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
        interests: ['Market Research', 'Data Analysis', 'Economics'],
        bio: 'Conducting market research to inform decisions',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '18',
        name: 'Benjamin King',
        role: 'Legal Advisor',
        company: 'Legal Path',
        imageUrl: 'https://randomuser.me/api/portraits/men/18.jpg',
        interests: ['Law', 'Contracts', 'Corporate Governance'],
        bio: 'Guiding businesses on legal matters',
        isAvailableForNetworking: false,
      ),
      Member(
        id: '19',
        name: 'Chloe Scott',
        role: 'Customer Success Manager',
        company: 'SuccessHub',
        imageUrl: 'https://randomuser.me/api/portraits/women/19.jpg',
        interests: ['Customer Service', 'Retention', 'Onboarding'],
        bio: 'Enhancing customer experience and retention',
        isAvailableForNetworking: true,
      ),
      Member(
        id: '20',
        name: 'Alexander Wright',
        role: 'Technical Writer',
        company: 'WriteIt',
        imageUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
        interests: ['Technical Writing', 'Documentation', 'Software'],
        bio: 'Making complex technology easy to understand',
        isAvailableForNetworking: true,
      ),
    ];
  }
}
